import logo from './logo.webp'
import hero from './hero.webp'
// import flash from './flash.webp'
import drone from './drone.svg'
import computer from './computer.svg'
import watch from './watch.svg'
import game from './game.svg'
import tv from './tv.svg'
import phoneTab from './phoneTab.svg'
import cam from './cam.svg'
import audio from './audio.svg'
import home from './home.svg'
import notFound from './not-found.png'
// export { default as OneStar } from './one-star.svg'
// export { default as TwoStar } from './two-star.svg'
// export { default as ThreeStar } from './three-star.svg'
// export { default as FourStar } from './four-star.svg'
// export { default as FiveStar } from './five-star.svg'

export {logo, drone, hero, computer, watch, game, tv, phoneTab, cam, audio, home, notFound}